more understandable + fail out with message

diff --git a/archiso/airootfs/usr/local/bin/aeros-update b/archiso/airootfs/usr/local/bin/aeros-update
--- a/archiso/airootfs/usr/local/bin/aeros-update
+++ b/archiso/airootfs/usr/local/bin/aeros-update
@@ -42,16 +42,26 @@ then
     read -p "Would you like to begin the update? [y/n] " -n 1 -r
     if [[ $REPLY =~ ^[Yy]$ ]]
     then
-        set -e
+        # If any commands have failed, quit immediately (IF THIS HAPPENED TO YOU, IMMEDIATELY REINSTALL AS YOUR SYSTEM IS NOW UNSTABLE)
+        try() { $1 || () { echo -n "System update failed to install.\nYour system is now unstable. Reinstall aerOS immediately."; exit 1 } }
         echo
-        wget $UPDATE_URL -O ~/update.tar.gz
-        pv ~/update.tar.gz | tar --xattrs --xattrs-include="*.*" --keep-directory-symlink --no-same-owner -C / -xpz
-        mkinitcpio -P
-        genfstab -U -p / > /etc/fstab
-        grub-mkconfig -o /boot/grub/grub.cfg
-        ( cd /var/lib/pacman/local && ls | sort | awk -v re='(.*)-[^-]*-[^-]*$' 'match($0, re, a) { if (!(a[1] in p)){p[a[1]]} else {print} }' | xargs rm -rf )
-        pacman --config=/etc/pacman-update.conf -Syu --overwrite="*" --noconfirm
-        rm -rf ~/update.tar.gz
+
+        # Get and apply update file (DO NOT MAKE THOSE WITH THE ISO, ALWAYS INSTALL FIRST)
+        try wget $UPDATE_URL -O ~/update.tar.gz
+        try pv ~/update.tar.gz | tar --xattrs --xattrs-include="*.*" --keep-directory-symlink --no-same-owner -C / -xpz
+
+        # Reset Pacman package manager
+        try rm -rf /etc/pacman.d/gnupg
+        try pacman-key --init
+        try pacman-key --populate
+        try pacman -Scc --noconfirm
+        ( try cd /var/lib/pacman/local && ls | sort | awk -v re='(.*)-[^-]*-[^-]*$' 'match($0, re, a) { if (!(a[1] in p)){p[a[1]]} else {print} }' | xargs rm -rf )
+
+        # Force update previously non-updated packages
+        try pacman --config=/etc/pacman-update.conf -Syu --overwrite="*" --noconfirm
+
+        # Clean-up after a finished update
+        try rm -rf ~/update.tar.gz
 
         echo "System update has been installed, a reboot is required to apply it."
         read -p "Would you like to reboot? [y/n] " -n 1 -r
